final barberMapList = [
  {
    "shopName": "Cut & Shave",
    "barberName": "Ahmad Ali",
    "barberContact": "+923044945128",
    "totalSeats": '5',
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "address": '27-D Gulburg-III Lahore',
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/barber_1.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Master Cut",
    "barberName": "Mr Shehbaz",
    "barberContact": "+923044945128",
    "totalSeats": '6',
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "address": '80-C Gulburg-III Lahore',
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/barber_4.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Smart Saloon",
    "barberName": "A. Usman",
    "barberContact": "+923044945128",
    "totalSeats": '4',
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "address": '101-A Gulburg-III Lahore',
    "isfavourite": false,
    "image":"assets/barber_3.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Cutting Edge",
    "barberName": "Abu Bakar",
    "barberContact": "+923044945128",
    "totalSeats": '5',
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "address": '20-G Gulburg-III Lahore',
    "isfavourite": true,
    "image":"assets/barber_2.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Cut & Shave",
    "barberName": "Ahmad Ali",
    "barberContact": "+923044945128",
    "totalSeats": '6',
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "address": '40-F Gulburg-III Lahore',
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/barber_1.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Master Cut",
    "barberName": "Mr Shehbaz",
    "barberContact": "+923044945128",
    "totalSeats": '3',
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "address": '30-D Gulburg-III Lahore',
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/barber_4.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Smart Saloon",
    "barberName": "A. Usman",
    "barberContact": "+923044945128",
    "totalSeats": '2',
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "address": '24-D Gulburg-III Lahore',
    "isfavourite": false,
    "image":"assets/barber_3.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Cutting Edge",
    "barberName": "Abu Bakar",
    "barberContact": "+923044945128",
    "totalSeats": '2',
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "address": '48-G Gulburg-III Lahore',
    "isfavourite": true,
    "image":"assets/barber_2.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  }
];

final topList = [
  {
    "shopName": "Cut & Shave",
    "barberName": "Ahmad Ali",
    "barberContact": "+923044945128",
    "totalSeats": '6',
    "rating": 5.0,
    "goodReviews": 900,
    "totalScore": 93.2,
    "address": '40-F Gulburg-III Lahore',
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/barber_1.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Master Cut",
    "barberName": "Mr Shehbaz",
    "barberContact": "+923044945128",
    "totalSeats": '3',
    "rating": 5.0,
    "goodReviews": 700,
    "totalScore": 72.2,
    "address": '30-D Gulburg-III Lahore',
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/barber_4.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Smart Saloon",
    "barberName": "A. Usman",
    "barberContact": "+923044945128",
    "totalSeats": '2',
    "rating": 2.5,
    "goodReviews": 600,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "address": '24-D Gulburg-III Lahore',
    "isfavourite": false,
    "image":"assets/barber_3.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  },
  {
    "shopName": "Cutting Edge",
    "barberName": "Abu Bakar",
    "barberContact": "+923044945128",
    "totalSeats": '2',
    "rating": 5.0,
    "goodReviews": 500,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "address": '48-G Gulburg-III Lahore',
    "isfavourite": true,
    "image":"assets/barber_2.jpg",
    "description": "Also known as hairdressers, barbers provide various hairdressing services to primarily male clientele. They cut, trim, style and color hair, as well as provide facial hair grooming and massages.",
  }
];
